### ISSUE TITLE
code release?

### ISSUE THREAD

**Issue by ninjasaid2k** [yhli123/Immiscible-Diffusion#1]

**Comment by yhli123** [comment]
So sorry I am really busy on internship these days. Will try to do it asap. So sorry for that.Yiheng LiOn Jul 10, 2024, at 23:18, Said ***@***.***> wrote:﻿

**Comment by yhli123** [comment]
Hi there! We have just released the first batch of code. We are working on other versions. Thanks so much for your patience!
